export const ActionTypes = {
    PARTY_RECIEVED: 'PARTY_RECIEVED',
    USER_INFO_UPDATED: 'USER_INFO_UPDATED',
    USER_JOINED: 'USER_JOINED',
    USER_FLED: 'USER_FLED',
    USER_KICKED: 'USER_KICKED',
    USER_PROMOTE: 'USER_PROMOTE'
};